import type { FastifyInstance } from 'fastify';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { supabaseRest } from './supabase.js';
function q(v:string){return encodeURIComponent(v)}
const COOKIE='avtodrom_admin_session',TTL=60*60*12;
function cookie(req:any){const raw=String(req.headers?.cookie||'');const x=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(COOKIE+'='));return x?decodeURIComponent(x.slice(COOKIE.length+1)):''}
function token(login:string){const s=String(process.env.ADMIN_SESSION_SECRET||'').trim();if(!s)throw Error('ADMIN_SESSION_SECRET sozlanmagan');const p=`${login}:${Date.now()}`,sig=createHmac('sha256',s).update(p).digest('hex');return Buffer.from(`${p}:${sig}`).toString('base64url')}
function valid(t:string){try{const s=String(process.env.ADMIN_SESSION_SECRET||'').trim(),a=Buffer.from(t||'','base64url').toString('utf8').split(':');if(!s||a.length<3)return false;const login=a[0],ts=Number(a[1]),sig=a.slice(2).join(':');if(!login||!Number.isFinite(ts)||Date.now()-ts>TTL*1000)return false;const e=createHmac('sha256',s).update(`${login}:${ts}`).digest('hex');const x=Buffer.from(sig),y=Buffer.from(e);return x.length===y.length&&timingSafeEqual(x,y)}catch{return false}}
async function guard(req:any){if(!valid(cookie(req)))throw Error('Admin login talab qilinadi')}
function setCookie(reply:any,t:string){reply.header('Set-Cookie',`${COOKIE}=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${TTL}`)}
function clearCookie(reply:any){reply.header('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}

export async function registerAdminPasswordRoutes(app:FastifyInstance){
app.post('/api/admin/login',async(req:any,reply:any)=>{const b=req.body||{};const login=String(b.login||'').trim(),password=String(b.password||''),el=String(process.env.ADMIN_LOGIN||'').trim(),ep=String(process.env.ADMIN_PASSWORD||'');if(!el||!ep||!process.env.ADMIN_SESSION_SECRET)return reply.code(500).send({ok:false,error:'Admin auth environment sozlanmagan'});if(login!==el||password!==ep)return reply.code(401).send({ok:false,error:'Login yoki parol noto‘g‘ri'});setCookie(reply,token(login));return{ok:true,login}});
app.post('/api/admin/logout',async(_:any,reply:any)=>{clearCookie(reply);return{ok:true}});
app.get('/api/admin/me',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,login:process.env.ADMIN_LOGIN||'admin'}}catch(e){return reply.code(401).send({ok:false,error:e instanceof Error?e.message:'Unauthorized'})}});

app.get('/api/admin/stats',async(req:any,reply:any)=>{try{await guard(req);const [users,ins,books,revs]=await Promise.all([supabaseRest<any[]>('users',{query:'?select=id,role,is_active,is_blocked'}),supabaseRest<any[]>('instructor_profiles',{query:'?select=id,is_available,rating,total_reviews'}),supabaseRest<any[]>('bookings',{query:'?select=id,status,booking_date'}),supabaseRest<any[]>('reviews',{query:'?select=id,status,rating'})]);const now=new Date(),a=new Date(now);a.setHours(0,0,0,0);const z=new Date(a);z.setDate(z.getDate()+1);const visible=revs.filter(r=>String(r.status)==='approved');const avg=visible.length?visible.reduce((s,r)=>s+Number(r.rating||0),0)/visible.length:0;return{ok:true,stats:{customers:users.filter(u=>u.role==='customer').length,instructors:ins.filter(i=>i.is_available).length,pendingBookings:books.filter(b=>String(b.status)==='pending').length,todayBookings:books.filter(b=>new Date(b.booking_date)>=a&&new Date(b.booking_date)<z).length,completedBookings:books.filter(b=>String(b.status)==='completed').length,reviews:visible.length,averageRating:Number(avg.toFixed(2))}}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Stats failed'})}});

app.get('/api/admin/instructors',async(req:any,reply:any)=>{try{await guard(req);const rows=await supabaseRest<any[]>('instructor_profiles',{query:'?select=id,user_id,rating,total_reviews,is_available,is_verified,created_at,user:users!instructor_profiles_user_id_fkey(id,telegram_id,phone,full_name,role,is_active,is_blocked)&order=created_at.desc'});return{ok:true,instructors:rows.map(x=>({...x,active:Boolean(x.is_available&&x.user?.is_active&&!x.user?.is_blocked),profile:x.user||{}}))}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Failed to load instructors'})}});

app.post('/api/admin/instructors',async(req:any,reply:any)=>{try{await guard(req);const b=req.body||{},tg=Number(b.telegram_id),first=String(b.first_name||'').trim(),last=String(b.last_name||'').trim(),phone=String(b.phone||'').trim(),username=String(b.username||'').trim();if(!Number.isSafeInteger(tg)||!tg)return reply.code(400).send({ok:false,error:'Telegram ID majburiy'});if(first.length<2)return reply.code(400).send({ok:false,error:'Ism majburiy'});const name=[first,last].filter(Boolean).join(' ');const old=await supabaseRest<any[]>('users',{query:`?telegram_id=eq.${q(String(tg))}&select=*`});let u=old[0];if(u){u=(await supabaseRest<any[]>('users',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(u.id)}`,body:JSON.stringify({full_name:name,phone:phone||null,role:'instructor',is_active:true,is_blocked:false,updated_at:new Date().toISOString()})}))[0]||u}else{u=(await supabaseRest<any[]>('users',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({telegram_id:tg,full_name:name,phone:phone||null,role:'instructor',is_active:true,is_blocked:false})}))[0]};let ip=(await supabaseRest<any[]>('instructor_profiles',{query:`?user_id=eq.${q(u.id)}&select=*`}))[0];if(!ip)ip=(await supabaseRest<any[]>('instructor_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:u.id,is_available:true,is_verified:true})}))[0];return reply.code(201).send({ok:true,instructor:{...ip,profile:u}})}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Instructor creation failed'})}});

app.patch('/api/admin/instructors/:id',async(req:any,reply:any)=>{try{await guard(req);const active=Boolean(req.body?.active),ip=(await supabaseRest<any[]>('instructor_profiles',{query:`?id=eq.${q(req.params.id)}&select=*`}))[0];if(!ip)return reply.code(404).send({ok:false,error:'Instruktor topilmadi'});await supabaseRest('instructor_profiles',{method:'PATCH',query:`?id=eq.${q(ip.id)}`,body:JSON.stringify({is_available:active,updated_at:new Date().toISOString()})});await supabaseRest('users',{method:'PATCH',query:`?id=eq.${q(ip.user_id)}`,body:JSON.stringify({is_active:active,is_blocked:!active,updated_at:new Date().toISOString()})});return{ok:true}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Instructor update failed'})}});

app.get('/api/admin/bookings',async(req:any,reply:any)=>{try{await guard(req);const st=String((req.query||{}).status||'');const parts=['select=*,customer:customer_id(id,full_name,phone,telegram_id),instructor:instructor_id(id,rating,user:user_id(id,full_name,phone,telegram_id)),course:course_id(id,name)','order=booking_date.desc'];if(st)parts.push(`status=eq.${q(st)}`);return{ok:true,bookings:await supabaseRest<any[]>('bookings',{query:`?${parts.join('&')}`})}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Failed to load bookings'})}});

app.patch('/api/admin/bookings/:id/status',async(req:any,reply:any)=>{try{await guard(req);const status=String(req.body?.status||'');const allowed=['pending','confirmed','rejected','cancelled','completed','no_show'];if(!allowed.includes(status))return reply.code(400).send({ok:false,error:'Bron holati noto‘g‘ri'});const body:any={status,updated_at:new Date().toISOString()};if(status==='confirmed'){body.confirmed_at=new Date().toISOString()}if(status==='rejected'||status==='cancelled'){body.cancellation_reason=String(req.body?.reason||'')||null;body.cancelled_at=new Date().toISOString()}const rows=await supabaseRest<any[]>('bookings',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(req.params.id)}`,body:JSON.stringify(body)});if(!rows[0])return reply.code(404).send({ok:false,error:'Bron topilmadi'});return{ok:true,booking:rows[0]}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Booking update failed'})}});

app.get('/api/admin/customers',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,customers:await supabaseRest<any[]>('users',{query:'?role=eq.customer&select=id,telegram_id,full_name,phone,is_active,is_blocked,created_at,updated_at&order=created_at.desc'})}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Failed to load customers'})}});
app.patch('/api/admin/customers/:id',async(req:any,reply:any)=>{try{await guard(req);const active=Boolean(req.body?.active),rows=await supabaseRest<any[]>('users',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(req.params.id)}&role=eq.customer`,body:JSON.stringify({is_active:active,is_blocked:!active,updated_at:new Date().toISOString()})});if(!rows[0])return reply.code(404).send({ok:false,error:'Foydalanuvchi topilmadi'});return{ok:true,customer:rows[0]}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Customer update failed'})}});

app.get('/api/admin/reviews',async(req:any,reply:any)=>{try{await guard(req);const rows=await supabaseRest<any[]>('reviews',{query:'?select=*,customer:customer_id(id,full_name,phone),instructor:instructor_id(id,rating,user:user_id(full_name))&order=created_at.desc'});return{ok:true,reviews:rows}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Failed to load reviews'})}});
app.patch('/api/admin/reviews/:id',async(req:any,reply:any)=>{try{await guard(req);const status=String(req.body?.status||'approved');const map:any={visible:'approved',hidden:'rejected',deleted:'rejected'};const s=map[status]||status;if(!['pending','approved','rejected'].includes(s))return reply.code(400).send({ok:false,error:'Sharh holati noto‘g‘ri'});const rows=await supabaseRest<any[]>('reviews',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(req.params.id)}`,body:JSON.stringify({status:s,moderated_at:new Date().toISOString()})});if(!rows[0])return reply.code(404).send({ok:false,error:'Sharh topilmadi'});return{ok:true,review:rows[0]}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Review update failed'})}});

app.get('/api/admin/pricing',async(req:any,reply:any)=>{try{await guard(req);const rows=await supabaseRest<any[]>('admin_settings',{query:'?key=in.(lesson_price,lesson_duration,booking_enabled,system_name)&select=key,value,updated_at'});const out:any={};rows.forEach(r=>out[r.key]=r.value);return{ok:true,settings:out}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Pricing load failed'})}});
app.put('/api/admin/pricing',async(req:any,reply:any)=>{try{await guard(req);const b=req.body||{},amount=Number(b.amount),minutes=Number(b.minutes);if(!Number.isFinite(amount)||amount<0)return reply.code(400).send({ok:false,error:'Narx noto‘g‘ri'});if(!Number.isInteger(minutes)||minutes<15||minutes>240)return reply.code(400).send({ok:false,error:'Davomiylik 15-240 daqiqa oralig‘ida bo‘lsin'});const now=new Date().toISOString();for(const x of [{key:'lesson_price',value:{amount,currency:'UZS'}},{key:'lesson_duration',value:{minutes}},{key:'booking_enabled',value:{enabled:b.booking_enabled!==false}}])await supabaseRest('admin_settings',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({...x,updated_at:now})});return{ok:true}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Pricing update failed'})}});
app.get('/api/admin/settings',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,settings:await supabaseRest<any[]>('admin_settings',{query:'?select=key,value,updated_at&order=key.asc'})}}catch(e){return reply.code(500).send({ok:false,error:e instanceof Error?e.message:'Settings load failed'})}});
app.put('/api/admin/settings/:key',async(req:any,reply:any)=>{try{await guard(req);const key=String(req.params.key||'').trim();if(!/^[a-z0-9_]+$/.test(key))return reply.code(400).send({ok:false,error:'Settings key noto‘g‘ri'});await supabaseRest('admin_settings',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({key,value:req.body||{},updated_at:new Date().toISOString()})});return{ok:true}}catch(e){return reply.code(400).send({ok:false,error:e instanceof Error?e.message:'Settings update failed'})}});
}
