import type { FastifyInstance } from 'fastify';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { supabaseRest } from './supabase.js';
import { sendBookingNotification } from './telegram.js';
const COOKIE='avtodrom_admin_session',TTL=60*60*12,q=(v:string)=>encodeURIComponent(v);
function cookie(req:any){const raw=String(req.headers?.cookie||'');const x=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(COOKIE+'='));if(!x)return '';try{return decodeURIComponent(x.slice(COOKIE.length+1))}catch{return ''}}
function secret(){return String(process.env.ADMIN_SESSION_SECRET||process.env.ADMIN_PASSWORD||'').trim()}
function token(login:string){const s=secret();if(!s)throw Error('ADMIN_SESSION_SECRET yoki ADMIN_PASSWORD sozlanmagan');const ts=Date.now(),p=`${login}:${ts}`,sig=createHmac('sha256',s).update(p).digest('hex');return Buffer.from(`${p}:${sig}`).toString('base64url')}
function valid(t:string){try{const s=secret(),loginExpected=String(process.env.ADMIN_LOGIN||'').trim(),d=Buffer.from(t||'','base64url').toString('utf8'),a=d.indexOf(':'),b=d.indexOf(':',a+1);if(!s||!loginExpected||a<=0||b<=a)return false;const login=d.slice(0,a),ts=Number(d.slice(a+1,b)),sig=d.slice(b+1);if(login!==loginExpected||!Number.isFinite(ts)||Date.now()-ts<0||Date.now()-ts>TTL*1000)return false;const e=createHmac('sha256',s).update(`${login}:${ts}`).digest('hex'),x=Buffer.from(sig),y=Buffer.from(e);return x.length===y.length&&timingSafeEqual(x,y)}catch{return false}}
async function guard(req:any){if(!valid(cookie(req))){const e:any=new Error('Admin login talab qilinadi');e.statusCode=401;throw e}}
function setCookie(reply:any,t:string){reply.header('Set-Cookie',`${COOKIE}=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${TTL}`)}function clearCookie(reply:any){reply.header('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`)}function err(reply:any,e:any,msg:string,status=500){return reply.code(e?.statusCode??status).send({ok:false,error:e?.message||msg})}
async function safe<T=any>(table:string,query:string){try{return await supabaseRest<T[]>(table,{query})}catch(e){console.error('Admin read failed',table,e);return [] as T[]}}
async function adminUser(){const r=await supabaseRest<any[]>('users',{query:'?role=eq.admin&is_active=eq.true&is_blocked=eq.false&select=*&limit=1'});if(!r[0])throw Error('Admin foydalanuvchisi topilmadi');return r[0]}

export async function registerAdminPasswordRoutes(app:FastifyInstance){
app.post('/api/admin/login',async(req:any,reply:any)=>{try{const login=String(req.body?.login||'').trim(),password=String(req.body?.password||''),el=String(process.env.ADMIN_LOGIN||'').trim(),ep=String(process.env.ADMIN_PASSWORD||'');if(!el||!ep)return err(reply,null,'ADMIN_LOGIN yoki ADMIN_PASSWORD Vercelda sozlanmagan',500);if(login!==el||password!==ep)return reply.code(401).send({ok:false,error:'Login yoki parol noto‘g‘ri'});setCookie(reply,token(login));return{ok:true,login}}catch(e){return err(reply,e,'Admin login failed')}});
app.post('/api/admin/logout',async(_req:any,reply:any)=>{clearCookie(reply);return{ok:true}});app.get('/api/admin/me',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,login:String(process.env.ADMIN_LOGIN||'admin')}}catch(e){return err(reply,e,'Unauthorized',401)}});

app.get('/api/admin/stats',async(req:any,reply:any)=>{try{await guard(req);const[users,ips,bookings,reviews,payments]=await Promise.all([safe<any>('users','?role=eq.customer&select=id'),safe<any>('instructor_profiles','?select=id,user_id,is_available,rating,total_reviews,is_verified'),safe<any>('bookings','?select=id,status,booking_date,created_at'),safe<any>('reviews','?select=id,status,rating'),safe<any>('payments','?select=id,amount,status,paid_at,created_at')]);const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);const today=bookings.filter((b:any)=>{const d=new Date(b.booking_date||b.created_at);return d>=s&&d<e});const paid=payments.filter((p:any)=>String(p.status||'').toLowerCase()==='paid').filter((p:any)=>{const d=new Date(p.paid_at||p.created_at);return d>=s&&d<e}).reduce((a:number,p:any)=>a+Number(p.amount||0),0);const rr=reviews.filter((r:any)=>['approved','visible'].includes(String(r.status||'').toLowerCase())).map((r:any)=>Number(r.rating||0)).filter(Number.isFinite);return{ok:true,stats:{customers:users.length,instructors:ips.filter((i:any)=>i.is_available&&i.is_verified!==false).length,pendingBookings:bookings.filter((b:any)=>b.status==='pending').length,todayBookings:today.length,completedBookings:bookings.filter((b:any)=>b.status==='completed').length,averageRating:rr.length?Number((rr.reduce((a:number,b:number)=>a+b,0)/rr.length).toFixed(2)):0,paidToday:paid}}}catch(e){return err(reply,e,'Stats failed')}});

app.get('/api/admin/instructors',async(req:any,reply:any)=>{try{await guard(req);const[ips,users]=await Promise.all([safe<any>('instructor_profiles','?select=*&order=created_at.desc'),safe<any>('users','?select=id,telegram_id,phone,full_name,role,is_active,is_blocked,created_at')]);const um=new Map(users.map((u:any)=>[String(u.id),u]));return{ok:true,instructors:ips.map((x:any)=>({...x,id:x.id,active:Boolean(x.is_available&&x.is_verified&&um.get(String(x.user_id))?.is_active&&!um.get(String(x.user_id))?.is_blocked),profile:um.get(String(x.user_id))||null}))}}catch(e){return err(reply,e,'Failed to load instructors')}});
app.post('/api/admin/instructors',async(req:any,reply:any)=>{try{await guard(req);const b=req.body||{},first=String(b.first_name||'').trim(),last=String(b.last_name||'').trim(),phone=String(b.phone||'').trim(),tg=b.telegram_id?Number(b.telegram_id):null;if(first.length<2)return reply.code(400).send({ok:false,error:'Ism majburiy'});let u:any=tg?(await safe<any>('users',`?telegram_id=eq.${q(String(tg))}&select=*&limit=1`))[0]:null;const full=[first,last].filter(Boolean).join(' ');if(u)u=(await supabaseRest<any[]>('users',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(u.id)}`,body:JSON.stringify({phone:phone||null,full_name:full,role:'instructor',is_active:true,is_blocked:false,updated_at:new Date().toISOString()})}))[0]||u;else u=(await supabaseRest<any[]>('users',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({telegram_id:tg,phone:phone||null,full_name:full,role:'instructor',is_active:true,is_blocked:false})}))[0];if(!u)throw Error('Instruktor foydalanuvchisi yaratilmadi');const ip=(await supabaseRest<any[]>('instructor_profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:u.id,experience_years:Number(b.experience_years||0),bio:String(b.bio||'').trim()||null,rating:0,total_reviews:0,is_verified:true,is_available:true})}))[0];return reply.code(201).send({ok:true,instructor:{...ip,profile:u,active:true}})}catch(e){return err(reply,e,'Instructor creation failed',400)}});
app.patch('/api/admin/instructors/:id',async(req:any,reply:any)=>{try{await guard(req);const id=String(req.params.id),b=req.body||{},ip=(await supabaseRest<any[]>('instructor_profiles',{query:`?id=eq.${q(id)}&select=*`}))[0];if(!ip)return reply.code(404).send({ok:false,error:'Instruktor topilmadi'});if(typeof b.active==='boolean'){await supabaseRest('instructor_profiles',{method:'PATCH',query:`?id=eq.${q(id)}`,body:JSON.stringify({is_available:b.active,updated_at:new Date().toISOString()})});await supabaseRest('users',{method:'PATCH',query:`?id=eq.${q(ip.user_id)}`,body:JSON.stringify({is_active:b.active,is_blocked:!b.active,updated_at:new Date().toISOString()})})}return{ok:true}}catch(e){return err(reply,e,'Instructor update failed',400)}});

app.get('/api/admin/bookings',async(req:any,reply:any)=>{try{await guard(req);const st=String(req.query?.status||''),filter=st?`&status=eq.${q(st)}`:'';const[bookings,users,ips,courses]=await Promise.all([supabaseRest<any[]>('bookings',{query:`?select=*&order=booking_date.desc${filter}`}),safe<any>('users','?select=id,telegram_id,phone,full_name,role'),safe<any>('instructor_profiles','?select=id,user_id,rating,total_reviews'),safe<any>('courses','?select=id,name,duration_minutes,price,is_active')]);const um=new Map(users.map((u:any)=>[String(u.id),u])),im=new Map(ips.map((i:any)=>[String(i.id),i])),cm=new Map(courses.map((c:any)=>[String(c.id),c]));return{ok:true,bookings:bookings.map((b:any)=>{const i=im.get(String(b.instructor_id)),c=cm.get(String(b.course_id)),u=i?um.get(String(i.user_id)):null;return{...b,start_at:b.start_at||b.booking_date,end_at:b.end_at||((b.booking_date&&c?.duration_minutes)?new Date(new Date(b.booking_date).getTime()+Number(c.duration_minutes)*60000).toISOString():null),price:b.price??c?.price??0,customer:um.get(String(b.customer_id))||null,instructor:i?{...i,profile:u||null}:null,course:c||null}})}}catch(e){return err(reply,e,'Failed to load bookings')}});
app.patch('/api/admin/bookings/:id/status',async(req:any,reply:any)=>{try{await guard(req);const id=String(req.params.id),status=String(req.body?.status||'');if(!['pending','confirmed','cancelled','rejected','in_progress','completed','no_show'].includes(status))return reply.code(400).send({ok:false,error:'Noto‘g‘ri bron holati'});const old=(await supabaseRest<any[]>('bookings',{query:`?id=eq.${q(id)}&select=*`}))[0];if(!old)return reply.code(404).send({ok:false,error:'Bron topilmadi'});const body:any={status,updated_at:new Date().toISOString()};if(status==='confirmed')body.confirmed_at=new Date().toISOString();if(['cancelled','rejected'].includes(status)){body.cancelled_at=new Date().toISOString();body.cancellation_reason=String(req.body?.reason||'').trim()||null}const rows=await supabaseRest<any[]>('bookings',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(id)}`,body:JSON.stringify(body)});try{const ip=old.instructor_id?(await safe<any>('instructor_profiles',`?id=eq.${q(String(old.instructor_id))}&select=user_id`))[0]:null;const u=ip?.user_id?(await safe<any>('users',`?id=eq.${q(String(ip.user_id))}&select=telegram_id`))[0]:null;const t=String(process.env.INSTRUCTOR_BOT_TOKEN||'');if(t&&u?.telegram_id)await sendBookingNotification(t,Number(u.telegram_id),`📋 AVTODROM\n\nBron #${id}\nHolati: ${status}`,String(process.env.INSTRUCTOR_MINI_APP_URL||''),'👨‍🏫 Instruktor paneli')}catch(e){console.error('Instructor notification failed',e)}return{ok:true,booking:rows[0]}}catch(e){return err(reply,e,'Booking update failed',400)}});

app.get('/api/admin/customers',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,customers:await safe<any>('users','?role=eq.customer&select=id,telegram_id,full_name,phone,role,is_active,is_blocked,created_at&order=created_at.desc')}}catch(e){return err(reply,e,'Failed to load customers')}});
app.patch('/api/admin/customers/:id',async(req:any,reply:any)=>{try{await guard(req);const id=String(req.params.id),b=req.body||{},patch:any={updated_at:new Date().toISOString()};if(typeof b.active==='boolean'){patch.is_active=b.active;patch.is_blocked=!b.active}if(b.full_name!==undefined)patch.full_name=String(b.full_name||'').trim();if(b.phone!==undefined)patch.phone=String(b.phone||'').trim()||null;const rows=await supabaseRest<any[]>('users',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(id)}&role=eq.customer`,body:JSON.stringify(patch)});return{ok:true,customer:rows[0]}}catch(e){return err(reply,e,'Customer update failed',400)}});

app.get('/api/admin/reviews',async(req:any,reply:any)=>{try{await guard(req);const[rows,users,ips]=await Promise.all([safe<any>('reviews','?select=*&order=created_at.desc'),safe<any>('users','?select=id,full_name,phone'),safe<any>('instructor_profiles','?select=id,user_id')]);const um=new Map(users.map((u:any)=>[String(u.id),u])),im=new Map(ips.map((i:any)=>[String(i.id),i]));return{ok:true,reviews:rows.map((r:any)=>{const ip=im.get(String(r.instructor_id));return{...r,customer:um.get(String(r.customer_id))||null,instructor:ip?{...ip,profile:um.get(String(ip.user_id))||null}:null}})}}catch(e){return err(reply,e,'Failed to load reviews')}});
app.patch('/api/admin/reviews/:id',async(req:any,reply:any)=>{try{await guard(req);const s=String(req.body?.status||'');if(!['pending','approved','rejected','visible','hidden','deleted'].includes(s))return reply.code(400).send({ok:false,error:'Sharh holati noto‘g‘ri'});const rows=await supabaseRest<any[]>('reviews',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?id=eq.${q(String(req.params.id))}`,body:JSON.stringify({status:s,updated_at:new Date().toISOString(),moderated_at:new Date().toISOString()})});return{ok:true,review:rows[0]}}catch(e){return err(reply,e,'Review update failed',400)}});

const applications=async(req:any,reply:any)=>{try{await guard(req);return{ok:true,applications:await supabaseRest<any[]>('instructor_applications',{query:'?select=*&order=created_at.desc'})}}catch(e){return err(reply,e,'Failed to load applications')}};app.get('/api/admin/applications',applications);app.get('/api/admin/instructor-applications',applications);
const approve=async(req:any,reply:any)=>{try{await guard(req);const admin=await adminUser();const rows=await supabaseRest<any[]>('rpc/admin_approve_instructor',{method:'POST',body:JSON.stringify({p_application_id:String(req.params.id),p_admin_id:admin.id})});return{ok:true,application:Array.isArray(rows)?rows[0]:rows}}catch(e){return err(reply,e,'Tasdiqlash amalga oshmadi',400)}};
const reject=async(req:any,reply:any)=>{try{await guard(req);const admin=await adminUser();const rows=await supabaseRest<any[]>('rpc/admin_reject_instructor',{method:'POST',body:JSON.stringify({p_application_id:String(req.params.id),p_admin_id:admin.id,p_reason:String(req.body?.reason||'').trim()||null})});return{ok:true,application:Array.isArray(rows)?rows[0]:rows}}catch(e){return err(reply,e,'Rad etish amalga oshmadi',400)}};app.post('/api/admin/applications/:id/approve',approve);app.post('/api/admin/applications/:id/reject',reject);app.post('/api/admin/instructor-applications/:id/approve',approve);app.post('/api/admin/instructor-applications/:id/reject',reject);

app.get('/api/admin/settings',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,settings:await safe<any>('admin_settings','?select=key,value,updated_at&order=key.asc')}}catch(e){return err(reply,e,'Failed to load settings')}});
app.put('/api/admin/settings/:key',async(req:any,reply:any)=>{try{await guard(req);const key=String(req.params.key),value=req.body?.value!==undefined?req.body.value:req.body;const old=await safe<any>('admin_settings',`?key=eq.${q(key)}&select=*`);if(old[0]){const rows=await supabaseRest<any[]>('admin_settings',{method:'PATCH',headers:{Prefer:'return=representation'},query:`?key=eq.${q(key)}`,body:JSON.stringify({value,updated_at:new Date().toISOString()})});return{ok:true,setting:rows[0]}}const rows=await supabaseRest<any[]>('admin_settings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({key,value,updated_at:new Date().toISOString()})});return{ok:true,setting:rows[0]}}catch(e){return err(reply,e,'Setting save failed',400)}});
app.get('/api/admin/courses',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,courses:await safe<any>('courses','?select=*&order=created_at.desc')}}catch(e){return err(reply,e,'Failed to load courses')}});app.get('/api/admin/payments',async(req:any,reply:any)=>{try{await guard(req);return{ok:true,payments:await safe<any>('payments','?select=*&order=created_at.desc')}}catch(e){return err(reply,e,'Failed to load payments')}});
}