import type { FastifyInstance } from 'fastify';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { supabaseRest } from './supabase.js';
import { sendBookingNotification } from './telegram.js';
const COOKIE_NAME='avtodrom_admin_session',SESSION_TTL=60*60*12,SUPABASE_URL=String(process.env.SUPABASE_URL||'').trim(),SERVICE_KEY=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim(),BUCKET='admin-media',WEB_ADMIN_ID='6d94122e-8b9f-4523-a304-ec2d2e85a003';
function q(v:string){return encodeURIComponent(v)}function getCookie(r:any){const raw=String(r.headers?.cookie??'');const item=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(`${COOKIE_NAME}=`));if(!item)return '';try{return decodeURIComponent(item.slice(COOKIE_NAME.length+1))}catch{return ''}}
function validSession(token:string){try{const fallback=String(process.env.ADMIN_PASSWORD||'').trim(),secret=String(process.env.ADMIN_SESSION_SECRET||fallback).trim(),login=String(process.env.ADMIN_LOGIN||'').trim();if(!secret||!login||!token)return false;const decoded=Buffer.from(token,'base64url').toString('utf8'),a=decoded.indexOf(':'),b=decoded.indexOf(':',a+1);if(a<=0||b<=a)return false;const actual=decoded.slice(0,a),ts=Number(decoded.slice(a+1,b)),sig=decoded.slice(b+1);if(actual!==login||!Number.isFinite(ts)||!sig)return false;const age=Date.now()-ts;if(age<0||age>SESSION_TTL*1000)return false;const expected=createHmac('sha256',secret).update(`${login}:${ts}`).digest('hex'),x=Buffer.from(sig),y=Buffer.from(expected);return x.length===y.length&&timingSafeEqual(x,y)}catch{return false}}
async function requireAdmin(r:any){if(!validSession(getCookie(r)))throw new Error('Unauthorized')}function publicUrl(path:string){return `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${path}`}
export function registerAdminDashboardRoutes(app:FastifyInstance){
app.get('/api/admin/applications',async(r,reply)=>{try{await requireAdmin(r);return{ok:true,applications:await supabaseRest<any[]>('instructor_applications',{query:'?select=*&order=created_at.desc'})}}catch(e:any){return reply.code(401).send({ok:false,error:e?.message||'Unauthorized'})}});
app.post<{Params:{id:string}}>('/api/admin/applications/:id/approve',async(r,reply)=>{try{await requireAdmin(r);const id=String(r.params.id),rows=await supabaseRest<any[]>('instructor_applications',{query:`?id=eq.${q(id)}&select=*`}),application=rows[0];if(!application)return reply.code(404).send({ok:false,error:'Ariza topilmadi'});const result=await supabaseRest<any[]>('rpc/admin_approve_instructor',{method:'POST',body:JSON.stringify({p_application_id:id,p_admin_id:WEB_ADMIN_ID})});try{const token=String(process.env.INSTRUCTOR_BOT_TOKEN||process.env.TELEGRAM_INSTRUCTOR_BOT_TOKEN||''),url=String(process.env.INSTRUCTOR_MINI_APP_URL||'https://avtodrom.vercel.app/instructor');if(token&&application.telegram_user_id)await sendBookingNotification(token,Number(application.telegram_user_id),'✅ Arizangiz tasdiqlandi!\n\nEndi AVTODROM Instruktor Mini Appiga kirishingiz mumkin.',url,'👨‍🏫 Instruktor panelini ochish')}catch(e){console.error('approval telegram notification failed',e)}return{ok:true,application:result?.[0]||application}}catch(e:any){return reply.code(400).send({ok:false,error:e?.message||'Tasdiqlash amalga oshmadi'})}});
app.post<{Params:{id:string};Body:{reason?:string}}>('/api/admin/applications/:id/reject',async(r,reply)=>{try{await requireAdmin(r);const id=String(r.params.id),reason=String(r.body?.reason||'').trim()||null,rows=await supabaseRest<any[]>('instructor_applications',{query:`?id=eq.${q(id)}&select=*`}),application=rows[0];if(!application)return reply.code(404).send({ok:false,error:'Ariza topilmadi'});const result=await supabaseRest<any[]>('rpc/admin_reject_instructor',{method:'POST',body:JSON.stringify({p_application_id:id,p_admin_id:WEB_ADMIN_ID,p_reason:reason})});try{const token=String(process.env.INSTRUCTOR_BOT_TOKEN||process.env.TELEGRAM_INSTRUCTOR_BOT_TOKEN||'');if(token&&application.telegram_user_id)await sendBookingNotification(token,Number(application.telegram_user_id),`❌ Arizangiz rad etildi.${reason?`\n\nSabab: ${reason}`:''}`)}catch(e){console.error('rejection telegram notification failed',e)}return{ok:true,application:result?.[0]||application}}catch(e:any){return reply.code(400).send({ok:false,error:e?.message||'Rad etish amalga oshmadi'})}});
app.get('/api/admin/notifications',async(r,reply)=>{try{await requireAdmin(r);return{ok:true,notifications:await supabaseRest<any[]>('notifications',{query:'?select=*&order=created_at.desc&limit=100'})}}catch(e:any){return reply.code(401).send({ok:false,error:e?.message||'Unauthorized'})}});
app.get('/api/admin/media',async(r,reply)=>{try{await requireAdmin(r);return{ok:true,media:await supabaseRest<any[]>('admin_media',{query:'?select=*&order=key.asc'})}}catch(e:any){return reply.code(401).send({ok:false,error:e?.message||'Unauthorized'})}});
app.post<{Body:{key:string;title:string;media_type:'image'|'video';file_name:string;content_type:string}}>('/api/admin/media/sign',async(r,reply)=>{try{await requireAdmin(r);if(!SUPABASE_URL||!SERVICE_KEY)return reply.code(500).send({ok:false,error:'Supabase server credentials are missing'});const key=String(r.body?.key||'').trim(),title=String(r.body?.title||'').trim(),mediaType=r.body?.media_type,fileName=String(r.body?.file_name||'file').replace(/[^a-zA-Z0-9._-]/g,'_'),contentType=String(r.body?.content_type||'application/octet-stream');if(!['home_image','guide_video'].includes(key))return reply.code(400).send({ok:false,error:'Noto‘g‘ri media kaliti'});if(!['image','video'].includes(String(mediaType)))return reply.code(400).send({ok:false,error:'Noto‘g‘ri media turi'});if(key==='home_image'&&!contentType.startsWith('image/'))return reply.code(400).send({ok:false,error:'Bu joyga faqat rasm yuklang'});if(key==='guide_video'&&!contentType.startsWith('video/'))return reply.code(400).send({ok:false,error:'Bu joyga faqat video yuklang'});const path=`${key}/${Date.now()}-${fileName}`,supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),{data,error}=await supabase.storage.from(BUCKET).createSignedUploadUrl(path,{upsert:true});if(error||!data?.token)throw new Error(error?.message||'Signed upload URL yaratilmadi');return{ok:true,path:`${BUCKET}/${path}`,storage_path:path,token:data.token,title:title||key,media_type:mediaType,public_url:publicUrl(path)}}catch(e:any){return reply.code(400).send({ok:false,error:e?.message||'Upload tayyorlashda xato'})}});
app.post<{Body:{key:string;title:string;media_type:'image'|'video';path:string;public_url:string}}>('/api/admin/media/commit',async(r,reply)=>{try{await requireAdmin(r);const key=String(r.body?.key||'').trim(),title=String(r.body?.title||'').trim(),mediaType=r.body?.media_type,path=String(r.body?.path||'').trim(),url=String(r.body?.public_url||'').trim();if(!['home_image','guide_video'].includes(key)||!['image','video'].includes(String(mediaType))||!path||!url)return reply.code(400).send({ok:false,error:'Media ma’lumotlari to‘liq emas'});const rows=await supabaseRest<any[]>('admin_media',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},query:'?on_conflict=key',body:JSON.stringify({key,title:title||key,media_type:mediaType,path:path.replace(`${BUCKET}/`,''),public_url:url,updated_at:new Date().toISOString()})});return{ok:true,media:rows[0]}}catch(e:any){return reply.code(400).send({ok:false,error:e?.message||'Media saqlanmadi'})}});
}
