import type { VercelRequest, VercelResponse } from '@vercel/node';
import { validateTelegramInitData } from '../../../../backend/src/telegram.js';
const U=process.env.SUPABASE_URL||'';const K=process.env.SUPABASE_SERVICE_ROLE_KEY||'';const T=process.env.INSTRUCTOR_BOT_TOKEN||process.env.TELEGRAM_INSTRUCTOR_BOT_TOKEN||'';
const out=(r:VercelResponse,s:number,b:any)=>r.status(s).setHeader('Content-Type','application/json').json(b);
const q=(v:string)=>encodeURIComponent(v);
function init(r:VercelRequest){const h=r.headers['x-telegram-init-data'];if(typeof h==='string'&&h.trim())return h.trim();const a=r.headers.authorization;if(typeof a==='string'&&a.toLowerCase().startsWith('tma '))return a.slice(4).trim();return typeof r.query?.initData==='string'?r.query.initData.trim():''}
async function auth(r:VercelRequest){if(!T)throw new Error('Instructor bot token is not configured');const d=init(r);if(!d)throw new Error('Telegram initData topilmadi');return validateTelegramInitData(d,T)}
async function rest(table:string,query:string){const x=await fetch(`${U}/rest/v1/${table}${query}`,{headers:{apikey:K,Authorization:`Bearer ${K}`}});const t=await x.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d={message:t}}if(!x.ok)throw new Error(d?.message||d?.hint||d?.details||`Supabase HTTP ${x.status}`);return d}
async function rpc(fn:string,body:any){const x=await fetch(`${U}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await x.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d={message:t}}if(!x.ok)throw new Error(d?.message||d?.hint||d?.details||d?.error||`Supabase HTTP ${x.status}`);return d}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=='POST')return out(res,405,{ok:false,error:'Method not allowed'});try{const u=await auth(req);const p=(await rest('profiles',`?telegram_id=eq.${q(String(u.id))}&select=*&limit=1`))[0];const i=p&&(await rest('instructors',`?profile_id=eq.${q(String(p.id))}&approved=eq.true&active=eq.true&select=*&limit=1`))[0];if(!p||!i)return out(res,403,{ok:false,error:'Instructor tasdiqlanmagan'});const id=String((req.query as any).id||'');const rows=await rpc('instructor_mark_arrived',{p_booking_id:id,p_instructor_id:i.id});const booking=Array.isArray(rows)?rows[0]:rows;return out(res,200,{ok:true,booking});}catch(e:any){const m=String(e?.message||'KELDI amalini bajarib bo‘lmadi');if(/BOOKING_NOT_FOUND/i.test(m))return out(res,404,{ok:false,error:'Bron topilmadi yoki bu instruktorga biriktirilmagan'});if(/BOOKING_NOT_CONFIRMED/i.test(m))return out(res,409,{ok:false,error:'KELDI faqat tasdiqlangan bron uchun mumkin.'});return out(res,400,{ok:false,error:m})}}
