import type { VercelRequest, VercelResponse } from '@vercel/node';
import { validateTelegramInitData, type TelegramWebAppUser } from '../../backend/src/telegram.js';

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const BOT_TOKEN = process.env.INSTRUCTOR_BOT_TOKEN || process.env.TELEGRAM_INSTRUCTOR_BOT_TOKEN || '';
function send(res: VercelResponse, status: number, body: unknown) { return res.status(status).setHeader('Content-Type','application/json').json(body); }
function q(v:string){return encodeURIComponent(v)}
function getInit(req:VercelRequest){const h=req.headers['x-telegram-init-data'];if(typeof h==='string'&&h.trim())return h.trim();const a=req.headers.authorization;if(typeof a==='string'&&a.toLowerCase().startsWith('tma '))return a.slice(4).trim();return typeof req.query?.initData==='string'?req.query.initData.trim():''}
async function auth(req:VercelRequest):Promise<TelegramWebAppUser>{if(!BOT_TOKEN)throw new Error('Instructor bot token is not configured');const d=getInit(req);if(!d)throw new Error('Telegram initData topilmadi');return validateTelegramInitData(d,BOT_TOKEN)}
async function rest<T>(table:string,query:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d={message:t}}if(!r.ok)throw new Error(d?.message||d?.hint||d?.details||`Supabase HTTP ${r.status}`);return d as T}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'});try{const u=await auth(req);const p=(await rest<any[]>('profiles',`?telegram_id=eq.${q(String(u.id))}&select=*&limit=1`))[0];if(!p||String(p.role||'').toLowerCase()!=='instructor'||p.active===false)return send(res,403,{ok:false,error:'Instructor hali Admin tomonidan tasdiqlanmagan',status:'PENDING'});const i=(await rest<any[]>('instructors',`?profile_id=eq.${q(String(p.id))}&approved=eq.true&active=eq.true&select=*&limit=1`))[0];if(!i)return send(res,403,{ok:false,error:'Instructor hali Admin tomonidan tasdiqlanmagan',status:'PENDING'});const from=typeof req.query?.from==='string'?req.query.from:'';const to=typeof req.query?.to==='string'?req.query.to:'';const parts=[`select=*,customer:customer_id(id,first_name,last_name,username,phone,telegram_id)`,`instructor_id=eq.${q(String(i.id))}`,'order=start_at.asc'];if(from)parts.push(`start_at=gte.${q(from)}`);if(to)parts.push(`start_at=lt.${q(to)}`);const bookings=await rest<any[]>('bookings',`?${parts.join('&')}`);return send(res,200,{ok:true,bookings});}catch(e:any){console.error('Instructor bookings API failed:',e);return send(res,400,{ok:false,error:String(e?.message||'Failed to load instructor bookings')})}}
