import { createHmac, timingSafeEqual } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

const COOKIE='avtodrom_admin_session';
const TTL=60*60*12;
const BUCKET='customer-media';
const url=()=>String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const key=()=>String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');
function getCookie(req:any){const raw=String(req.headers?.cookie||'');const x=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(COOKIE+'='));if(!x)return '';try{return decodeURIComponent(x.slice(COOKIE.length+1))}catch{return ''}}
function auth(req:any){const t=getCookie(req);const secret=String(process.env.ADMIN_SESSION_SECRET||process.env.ADMIN_PASSWORD||'').trim();const loginExpected=String(process.env.ADMIN_LOGIN||'').trim();if(!secret||!loginExpected||!t)throw Error('Unauthorized');try{const d=Buffer.from(t,'base64url').toString('utf8'),a=d.indexOf(':'),b=d.indexOf(':',a+1);if(a<=0||b<=a)throw Error();const login=d.slice(0,a),ts=Number(d.slice(a+1,b)),sig=d.slice(b+1);if(login!==loginExpected||!Number.isFinite(ts)||Date.now()-ts<0||Date.now()-ts>TTL*1000)throw Error();const exp=createHmac('sha256',secret).update(`${login}:${ts}`).digest('hex');const x=Buffer.from(sig),y=Buffer.from(exp);if(x.length!==y.length||!timingSafeEqual(x,y))throw Error();}catch{throw Error('Unauthorized')}}
function json(res:any,status:number,data:any){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(data))}
async function rest(table:string,q:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',key());h.set('Authorization',`Bearer ${key()}`);h.set('Content-Type','application/json');const r=await fetch(`${url()}/rest/v1/${table}${q}`,{...init,headers:h});const text=await r.text();if(!r.ok)throw Error(`Supabase ${r.status}: ${text||'request failed'}`);return text?JSON.parse(text):[]}
const esc=(v:string)=>encodeURIComponent(v);
export default async function handler(req:any,res:any){try{auth(req);if(req.method==='GET'){const [profiles,users]=await Promise.all([rest('instructor_profiles','?select=*&order=created_at.desc'),rest('users','?select=id,telegram_id,phone,full_name,role,is_active,is_blocked,created_at')]);const um=new Map(users.map((u:any)=>[String(u.id),u]));return json(res,200,{ok:true,instructors:profiles.map((p:any)=>{const u=um.get(String(p.user_id))||{};return {...p,id:p.id,active:Boolean(p.is_available&&p.is_verified&&u.is_active&&!u.is_blocked),profile:u}})});}if(req.method==='POST'){const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const first=String(b.first_name||'').trim(),last=String(b.last_name||'').trim();if(first.length<2)return json(res,400,{ok:false,error:'Ism majburiy'});const full=[first,last].filter(Boolean).join(' ');const tg=b.telegram_id?Number(b.telegram_id):null;let u=tg?(await rest('users',`?telegram_id=eq.${esc(String(tg))}&select=*&limit=1`))[0]:null;if(u){u=(await rest('users',`?id=eq.${esc(String(u.id))}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({full_name:full,phone:String(b.phone||'').trim()||null,role:'instructor',is_active:true,is_blocked:false,updated_at:new Date().toISOString()})}))[0]||u}else{u=(await rest('users','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({telegram_id:tg,phone:String(b.phone||'').trim()||null,full_name:full,role:'instructor',is_active:true,is_blocked:false})}))[0]}
if(!u)return json(res,400,{ok:false,error:'Instruktor foydalanuvchisi yaratilmadi'});const p=(await rest('instructor_profiles','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:u.id,experience_years:Number(b.experience_years||0),bio:String(b.bio||'').trim()||null,vehicle_model:String(b.vehicle_model||'').trim()||null,vehicle_plate:String(b.vehicle_plate||'').trim()||null,license_category:String(b.license_category||'B').trim()||'B',photo_url:String(b.photo_url||'').trim()||null,rating:0,total_reviews:0,is_verified:true,is_available:true})}))[0];return json(res,201,{ok:true,instructor:{...p,profile:u,active:true}})}return json(res,405,{ok:false,error:'Method not allowed'})}catch(e:any){json(res,e?.message==='Unauthorized'?401:400,{ok:false,error:e?.message||'Admin instructor API xatosi'})}}